### PR TITLE
Fix dependencies for lens-doc

### PR DESCRIPTION
**Pull request by LeifAndersen**

### CODE REVIEW

**Comment by lexi-lambda** [comment]
No, `struct-update-doc` intentionally avoids the dependency on `lens-doc`. It will generate a link if you already have the `lens` package installed, but otherwise it will just leave the link unrendered. The reason for this is that `lens` is a much heavier package than `struct-update`, and you should be able to install the `struct-update` package and its documentation without installing `lens`.

Ideally, I’d like the package system to have an “optional dependencies” section or something like that for this case, but for now it just needs to be left out.

**Comment by LeifAndersen** [comment]
Ah...hmm...I see. That totally is just a dynamic require. I wonder why it was unhappy then. :/ Seems like it probably is just due to how the dependency checker works.

**Comment by LeifAndersen** [comment]
Ya, there is certainly something odd going on here, from the deps docs:

> Dynamic references, such as through dynamic-require, are not visible to the dependency checker ...

And you seem to require something at runtime....so hmpph.

**Comment by LeifAndersen** [comment]
And double hmmph...even in the expanded code it still is only doing a dynamic-require. (Which is at least what you would expect...)

**Comment by LeifAndersen** [comment]
OH.....bleh, I think I got it. The dependency checker actually checks doc dependencies based on what scribble files link to each other, even if they're linked with a dynamic-require...hmph.

**Pull request closed without merging**
